## Библиотека Numpy

---

Пакет `numpy` предоставляет интерфейс для работы с $n$-мерными массивами. В `numpy` реализовано множество всевозможных операций над массивами в целом. Если задачу можно решить, произведя некоторую последовательность операций над массивами, то с помощью numpy в python это будет столь же эффективно, как в `C` или `matlab`.

## Одномерные массивы

### Создание массива 

In [ ]:
# принято, что numpy импортируют именно так
import numpy as np

Как же завести массив в numpy?

Очень просто! Надо всего лишь перевести обычный python list в np.array:

In [ ]:
# 'перевести' python list в np.array -- это обернуть массив в np.array()
a = np.array([3, 4, 1])
print(a)
type(a)

[3 4 1]


numpy.ndarray

Обычный питоновский `print` печатает массивы в удобной форме (точно так же, как и list питона)

In [ ]:
print(a)

[3 4 1]


### Типы данных в массивах np.array

Поговорим о типах данных, хранящихся в массивах:

Чаще всего мы будем работать с числовыми массивами, поэтому поговорим о инх.

В отличие от чистого питона, в `numpy` есть несколько типов для целых чисел (`int16`, `int32`, `int64`) и чисел с плавающей точкой (`float32`, `float64`). Они отличаются тем, с какой точностью в памяти хранятся элементы массива. 

Чтобы посмотреть, какой тип у вашего массива, можно вывести его dtype:

In [ ]:
a.dtype

dtype('int64')

Конечно, можно скастовать массив из одного типа в другой. 

Давайте переведем наш массив 'a' из типа np.int64 в тип np.float32:

In [ ]:
a = a.astype(np.float32)
a.dtype

dtype('float32')

Далее мы будем рассматривать n-мерный массивы, для них преобразование типов работает так же. И для них все еще все элементы должны иметь одинаковый тип.

### Изменение массивов np.array

Как и list в питоне, массивы np.array - изменяемые объекты. Механика изменений значений в них такая же, как у питоновских list'ов. Давайте в этом убедимся:

In [ ]:
a = np.array([3, 4 ,1])

a[1] = 3
print(a)

[3 3 1]


Единственный (но логичный) нюанс: при изменении значения в массиве с элементами одного типа на элемент другого типа новый элемент будет приведен к типу массива:

In [ ]:
# или: a = np.array([3, 4 ,1], dtype=np.int64)
a = np.array([3, 4 ,1]).astype(np.int64)

# значение 3.5 будет приведено к типу int64, т.е. станет 3
a[1] = 3.5
print(a)

[3 3 1]


In [ ]:
# обратите внимание -- если создается np.array с чисоами разных типов (int и float), 
# то все числа будут приведены к более точному типу, т.е. float
# таким образом, 1 из целого числа станет числом с плавающей точкой 1.
a = np.array([3., 4. ,1])

# значение 5 будет приведено к типу int64, т.е. станет 5.
a[1] = 5
print(a)

[3. 5. 1.]


А вот добавить к массиву новый элемент в конец чуть сложнее, чем у list. Напомним, в list это делалось с помощью метода .append(). В numpy это также делается с помощью append, но чуть по-другому:

Обратите внимание, что в numpy при append *создается новый массив*, а не происходит добавление элемента в уже существующий массив. Поэтому не рекомендуется создавать массивы с помощью append в numpy.

In [ ]:
a = np.array([3, 4 ,1])

# вот так пишется append
a = np.append(a, 6)

a

array([3, 4, 1, 6])

## Многомерные массивы

Мы узнали, как создавать и изменять одномерные массивы, как они выглядят в numpy и нюансы приведения типов. Настало время познакомиться с многомерными массивами.

Многомерный массив -- это массив, элементы которого тоже массивы. В принципе, ничего нового, все как и у list в питоне. 

In [ ]:
two_dim_array = np.array([[2, 3], [4, 5]])

print(two_dim_array)

[[2 3]
 [4 5]]


In [ ]:
three_dim_array = np.array([[[2, 3], [4, 5]], [[5, 6], [7, 8]]])

print(three_dim_array)

[[[2 3]
  [4 5]]

 [[5 6]
  [7 8]]]


Напомним, что в numpy, неважно, в одномерном или многомерном массиве, *все* элементы имеют одинаковый тип

Давайте в этом убедимся:

In [ ]:
# 2 и 3 приведутся к типу чисел 4. и 5., т.е. float64
a = np.array([[2, 3], [4., 5.]])
print(a, a.dtype)



[[2. 3.]
 [4. 5.]] float64


## Операции над одномерными массивами


 ### Арифметические операции

In [ ]:
a = np.array([2, 5, 6, 7])
b = np.array([9, 7, 8, 9])

С двумя массивами одинаковой 

In [ ]:
print(a + b)

[11 12 14 16]


In [ ]:
print(a - b)

[-7 -2 -2 -2]


In [ ]:
print(a * b)

[18 35 48 63]


In [ ]:
print(a / b)

[0.22222222 0.71428571 0.75       0.77777778]


In [ ]:
print(a ** 2)

[ 4 25 36 49]


`numpy` содержит элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (`ufunc`).

In [ ]:
np.sin, type(np.sin)

(<ufunc 'sin'>, numpy.ufunc)

In [ ]:
print(np.sin(a))
print(np.cosh(a))

[ 0.90929743 -0.95892427 -0.2794155   0.6569866 ]
[  3.76219569  74.20994852 201.71563612 548.31703516]


Один из операндов может быть скаляром, а не массивом.

In [ ]:
a

array([2, 5, 6, 7])

In [ ]:
print(a + 1)

[3 6 7 8]


In [ ]:
print(2 * a)

[ 4 10 12 14]


Сравнения дают булевы массивы.

In [ ]:
print(a > b)

[False False False False]


In [ ]:
print(a < b)

[ True  True  True  True]


In [ ]:
print(a == b)

[False False False False]


In [ ]:
c = a > 5
print(c)

[False False  True  True]


Кванторы "существует" и "для всех".

In [ ]:
np.any(c), np.all(c)

(True, False)

Модификация на месте.

In [ ]:
a += 1
print(a)

[3 6 7 8]


In [ ]:
b *= 2
print(b)

[18 14 16 18]


При выполнении операций над массивами деление на 0 не возбуждает исключения, а даёт значения `np.nan` или `np.inf`.

In [ ]:
np.nan + 1, np.inf + 1, np.inf * 0, 1. / np.inf

(nan, inf, nan, 0.0)

Сумма и произведение всех элементов массива; максимальный и минимальный элемент; среднее и среднеквадратичное отклонение.

In [ ]:
b.sum(), b.prod(), b.max(), b.min(), b.mean(), b.std()

(66, 72576, 18, 14, 16.5, 1.6583123951777)

In [ ]:
x = np.random.normal(size=1000)
x.mean(), x.std()

(0.01507805525557629, 0.9799831319251014)

Имеются встроенные функции

In [ ]:
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b + 1))
print(np.sin(b))
print(np.e, np.pi)

[4.24264069 3.74165739 4.         4.24264069]
[65659969.13733051  1202604.28416478  8886110.52050787 65659969.13733051]
[2.94443898 2.7080502  2.83321334 2.94443898]
[-0.75098725  0.99060736 -0.28790332 -0.75098725]
2.718281828459045 3.141592653589793


Иногда бывает нужно использовать частичные (кумулятивные) суммы. В нашем курсе такое пригодится.

In [ ]:
print(b.cumsum()[::-1])

[66 48 32 18]


Функция `sort` возвращает отсортированную копию, метод `sort` сортирует на месте.

In [ ]:
print(np.sort(b))
print(b)

[14 16 18 18]
[18 14 16 18]


In [ ]:
b.sort()
print(b)

[14 16 18 18]


Объединение массивов "по-горизонтали" (horizontal stack).

In [ ]:
a = np.array([1, 2, 3])
b = np.array([100, 200, 300])

print(np.hstack((a, b)))

[  1   2   3 100 200 300]


Объединение массивов "по-вертикали" (vertical stack).

In [ ]:
print(np.vstack((a, b)))

[[  1   2   3]
 [100 200 300]]


Расщепление массива в позициях 3 и 6.

In [ ]:
a = np.random.random(10)
np.hsplit(a, [3, 6])

[array([0.61994744, 0.97185517, 0.52760736]),
 array([0.49960358, 0.75170935, 0.14125351]),
 array([0.67908283, 0.52605088, 0.88374089, 0.54389519])]

Функции `delete`, `insert` и `append` не меняют массив на месте, а возвращают новый массив, в котором удалены, вставлены в середину или добавлены в конец какие-то элементы.

In [ ]:
a = np.arange(10)

In [ ]:
a = np.delete(a, [5, 7])
print(a)

[0 1 2 3 4 6 8 9]


In [ ]:
a = np.insert(a, 2, [0, 0])
print(a)

[0 1 0 0 2 3 4 6 8 9]


In [ ]:
a = np.append(a, [1, 2, 3])
print(a)

[0 1 0 0 2 3 4 6 8 9 1 2 3]


Есть несколько способов индексации массива. Вот обычный индекс.

In [ ]:
a = np.linspace(0, 1, 11)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
b = a[2]
print(b)

0.2


Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.

In [ ]:
b = a[2:6]
print(b)

[0.2 0.3 0.4 0.5]


In [ ]:
b[0] = -0.2
print(b)

[-0.2  0.3  0.4  0.5]


In [ ]:
print(a)

[ 0.   0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Диапазон с шагом 2.

In [ ]:
b = a[1:10:2]
print(b)

[0.1 0.3 0.5 0.7 0.9]


In [ ]:
b[0] = -0.1
print(a)

[ 0.  -0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Массив в обратном порядке.

In [ ]:
b = a[len(a):0:-1]
print(b)

[ 1.   0.9  0.8  0.7  0.6  0.5  0.4  0.3 -0.2 -0.1]


Подмассиву можно присвоить значение - массив правильного размера или скаляр.

In [ ]:
a[1:10:3] = 0
print(a)

[ 0.   0.  -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Тут опять создаётся только новый заголовок, указывающий на те же данные.

In [ ]:
b = a[:]
b[1] = 0.1
print(a)

[ 0.   0.1 -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Чтобы скопировать и данные массива, нужно использовать метод `copy`.

In [ ]:
b = a.copy()
b[2] = 0
print(b)
print(a)

[0.  0.1 0.  0.3 0.  0.5 0.6 0.  0.8 0.9 1. ]
[ 0.   0.1 -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Можно задать список индексов.

In [ ]:
print(a[[2, 3, 5]])

[-0.2  0.3  0.5]


Можно задать булев массив той же величины.

In [ ]:
b = a > 0
print(b)

[False  True False  True False  True  True False  True  True  True]


In [ ]:
print(a[b])

[0.1 0.3 0.5 0.6 0.8 0.9 1. ]


## 2-мерные массивы

In [ ]:
a = np.array([[0.0, 1.0], [-1.0, 0.0]])
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 2)

In [ ]:
len(a), a.size

(2, 4)

In [ ]:
a[1, 0]

-1.0

Атрибуту `shape` можно присвоить новое значение - кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.

In [ ]:
b = np.linspace(0, 3, 4)
print(b)

[0. 1. 2. 3.]


In [ ]:
b.shape

(4,)

In [ ]:
b.shape = 2, 2
print(b)

[[0. 1.]
 [2. 3.]]


Можно растянуть в одномерный массив

In [ ]:
print(b.ravel())

[0. 1. 2. 3.]


Арифметические операции поэлементные

In [ ]:
a

array([[ 0.,  1.],
       [-1.,  0.]])

In [ ]:
b = np.array([[3, 4], 
    [8, 6 ]])
print(b)

[[3 4]
 [8 6]]


In [ ]:
print(a + 1)
print(a * 2)
print(a + [0, 1])  # второе слагаемое дополняется до матрицы копированием строк
print(a + np.array([[0, 2]]).T)  # .T - транспонирование
print(a + b)

[[1. 2.]
 [0. 1.]]
[[ 0.  2.]
 [-2.  0.]]
[[ 0.  2.]
 [-1.  1.]]
[[0. 1.]
 [1. 2.]]
[[3. 5.]
 [7. 6.]]


Поэлементное и матричное (начиная с Python 3.5) умножение.

In [ ]:
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [ ]:
print(b)

[[3 4]
 [8 6]]


In [ ]:
print(a * b)

[[ 0.  4.]
 [-8.  0.]]


In [ ]:
print(a @ b)

[[ 8.  6.]
 [-3. -4.]]


In [ ]:
print(b @ a)

[[-4.  3.]
 [-6.  8.]]


Умножение матрицы на вектор.

In [ ]:
v = np.array([1, -1], dtype=np.float64)
print(b @ v)

[-1.  2.]


In [ ]:
print(v @ b)

[-5. -2.]


Единичная матрица.

In [ ]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Метод `reshape` делает то же самое, что присваивание атрибуту `shape`.

In [ ]:
print(I.reshape(16))

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [ ]:
print(I.reshape(8, 2))

[[1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]]


Строка.

In [ ]:
print(I[2])

[0. 0. 1. 0.]


Цикл по строкам.

In [ ]:
for row in I:
    print(row)

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


Столбец.

In [ ]:
print(I[1, 1])

1.0


Подматрица.

In [ ]:
print(I[0:2, 1:3])

[[0. 0.]
 [1. 0.]]


Можно построить двумерный массив из функции.

In [ ]:
def f(i, j):
    print(i)
    print(j)
    return 10 * i + j

print(np.fromfunction(f, (4, 4), dtype=np.int64))

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


Транспонированная матрица.

In [ ]:
print(b.T)

[[3 8]
 [4 6]]


Соединение матриц по горизонтали и по вертикали.

In [ ]:
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[4, 5], [6, 7], [8, 9]])
print(a)
print(b)
print(c)

[[0 1]
 [2 3]]
[[4 5 6]
 [7 8 9]]
[[4 5]
 [6 7]
 [8 9]]


In [ ]:
print(np.hstack((a, b)))

[[0 1 4 5 6]
 [2 3 7 8 9]]


In [ ]:
print(np.vstack((a, c)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Сумма всех элементов; суммы столбцов; суммы строк.

In [ ]:
b

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

39
[11 13 15]
[15 24]


Аналогично работают `prod`, `max`, `min` и т.д.

In [ ]:
print(b.max())
print(b.max(axis=0))
print(b.min(axis=1))

9
[7 8 9]
[4 7]


След - сумма диагональных элементов.

In [ ]:
np.trace(a)

3

## Линейная алгебра

In [ ]:
np.linalg.det(a)

-2.0

Обратная матрица.

In [ ]:
a1 = np.linalg.inv(a)
print(a1)

[[-1.5  0.5]
 [ 1.   0. ]]


In [ ]:
print(a @ a1)
print(a1 @ a)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


Решение линейной системы $au=v$.

In [ ]:
v = np.array([0, 1], dtype=np.float64)
print(a1 @ v)

[0.5 0. ]


In [ ]:
u = np.linalg.solve(a, v)
print(u)

[0.5 0. ]


Проверим.

In [ ]:
print(a @ u - v)

[0. 0.]


Собственные значения и собственные векторы: $a u_i = \lambda_i u_i$. `l` - одномерный массив собственных значений $\lambda_i$, столбцы матрицы $u$ - собственные векторы $u_i$.

In [ ]:
l, u = np.linalg.eig(a)
print(l)

[-0.56155281  3.56155281]


In [ ]:
print(u)

[[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


Проверим.

In [ ]:
for i in range(2):
    print(a @ u[:, i] - l[i] * u[:, i])

[0.00000000e+00 1.66533454e-16]
[ 0.0000000e+00 -4.4408921e-16]


Функция `diag` от одномерного массива строит диагональную матрицу; от квадратной матрицы - возвращает одномерный массив её диагональных элементов.

In [ ]:
L = np.diag(l)
print(L)
print(np.diag(L))

[[-0.56155281  0.        ]
 [ 0.          3.56155281]]
[-0.56155281  3.56155281]


Все уравнения $a u_i = \lambda_i u_i$ можно собрать в одно матричное уравнение $a u = u \Lambda$, где $\Lambda$ - диагональная матрица с собственными значениями $\lambda_i$ на диагонали.

In [ ]:
print(a @ u - u @ L)

[[ 0.00000000e+00  0.00000000e+00]
 [ 1.66533454e-16 -4.44089210e-16]]


Поэтому $u^{-1} a u = \Lambda$.

In [ ]:
print(np.linalg.inv(u) @ a @ u)

[[-5.61552813e-01  2.77555756e-17]
 [-2.22044605e-16  3.56155281e+00]]


Найдём теперь левые собственные векторы $v_i a = \lambda_i v_i$ (собственные значения $\lambda_i$ те же самые).

In [ ]:
l, v = np.linalg.eig(a.T)
print(l)
print(v)

[-0.56155281  3.56155281]
[[-0.96276969 -0.48963374]
 [ 0.27032301 -0.87192821]]


Собственные векторы нормированы на 1.

In [ ]:
print(u.T @ u)
print(v.T @ v)

[[ 1.         -0.23570226]
 [-0.23570226  1.        ]]
[[1.         0.23570226]
 [0.23570226 1.        ]]


Левые и правые собственные векторы, соответствующие разным собственным значениям, ортогональны, потому что $v_i a u_j = \lambda_i v_i u_j = \lambda_j v_i u_j$.

In [ ]:
print(v.T @ u)

[[ 9.71825316e-01  0.00000000e+00]
 [-5.55111512e-17  9.71825316e-01]]
